import { createContext, useContext, useEffect, useMemo, useState } from 'react';
import type { Dispatch, ReactNode, SetStateAction } from 'react';
import type { Activity, Area, HabitName, Mode, Plan, Store, Topic, WorkoutPlan } from './types';
const key='growth-os-v3';
const legacyKey='growth-os-v2';
export const modes:Mode[]=['College Day','Weekend','Holiday','Festival','Exam Mode'];
export const habits:HabitName[]=['Workout','Water Intake','Sleep','Meditation'];
export const uid=()=>Math.random().toString(36).slice(2,10);
export const dateKey=(d=new Date())=>{const local=new Date(d.getTime()-d.getTimezoneOffset()*60000);return local.toISOString().slice(0,10)};
export const createTopics=(count:number):Topic[]=>Array.from({length:count},(_,i)=>({id:uid(),title:`Topic ${i+1}`,done:false}));
export const createArea=(name:string,planned=20):Area=>({id:uid(),name,planned,topics:[]});
export const defaultWorkout=(mode:Mode)=>mode==='College Day'?'5:15 PM – 6:15 PM Workout':mode==='Weekend'||mode==='Holiday'?'4:00 PM – 5:00 PM Workout':'Optional';
const workoutDefaults=():Record<Mode,string>=>Object.fromEntries(modes.map(mode=>[mode,defaultWorkout(mode)])) as Record<Mode,string>;
const weeklyWorkouts=():Record<number,WorkoutPlan>=>({1:{title:'Dance + Glutes 🍑',channels:['GrowwithJo','MadFit']},2:{title:'Dance Day 🎵',channels:['GrowwithJo']},3:{title:'Dance + Legs 🦵',channels:['GrowwithJo','Juice & Toya']},4:{title:'Dance + Core 💚',channels:['Fitness Marshall','MadFit']},5:{title:'Dance + Glutes 🍑',channels:['GrowwithJo','MadFit']},6:{title:'Fun Dance ✨',channels:['Fitness Marshall']},0:{title:'Recovery & Stretch 🧘',channels:['Yoga With Adriene']}});
const periodWorkouts=():WorkoutPlan[]=>[{title:'Period Day 1 · Rest & Gentle Care',channels:['Yoga With Adriene']},{title:'Period Day 2 · Gentle Stretch',channels:['Yoga With Adriene']},{title:'Period Day 3 · Low-Impact Dance',channels:['GrowwithJo']},{title:'Period Day 4 · Gentle Core & Mobility',channels:['MadFit']},{title:'Period Day 5 · Recovery Flow',channels:['Yoga With Adriene']}];
const blankPlan=(mode:Mode):Plan=>({mode,learningAreaId:'',focus:'',priority:'',study:'',workout:defaultWorkout(mode),notes:''});
const items=(...x:[string,string][]):Activity[]=>x.map(([time,activity])=>({id:uid(),time,activity}));
const defaultTimetables=():Record<Mode,Activity[]>=>({'College Day':items(['4:00 AM – 5:00 AM','Book Writing'],['5:00 AM – 6:30 AM','College Revision'],['6:30 AM – 8:00 AM','Breakfast • Get Ready • Travel'],['8:00 AM – 4:00 PM','College'],['4:00 PM – 4:45 PM','Rest + Snack'],['4:45 PM – 5:15 PM','Call Time'],['5:15 PM – 6:15 PM','Workout'],['6:15 PM – 7:00 PM','Dinner'],['7:00 PM – 8:00 PM','College Study'],['8:00 PM – 9:30 PM','Career Growth Study'],['9:30 PM','Sleep Preparation']),'Weekend':items(['8:00 AM – 8:30 AM','Wake Up'],['8:30 AM – 9:00 AM','Breakfast'],['9:00 AM – 11:30 AM','Deep Study Session'],['11:30 AM – 12:00 PM','Break'],['12:00 PM – 1:00 PM','Study'],['1:00 PM – 2:00 PM','Lunch'],['2:00 PM – 4:00 PM','Career Growth Study'],['4:00 PM – 5:00 PM','Workout'],['5:00 PM – 6:00 PM','Freshen Up'],['6:00 PM – 8:00 PM','Projects'],['8:00 PM – 9:00 PM','Dinner'],['9:00 PM – 10:00 PM','Entertainment / Family'],['10:00 PM – 10:30 PM','Weekly Review & Plan Next Week'],['10:30 PM','Sleep']),'Holiday':items(['8:00 AM – 8:30 AM','Wake Up'],['8:30 AM – 9:00 AM','Breakfast'],['9:00 AM – 11:30 AM','Study'],['11:30 AM – 1:00 PM','Projects'],['1:00 PM – 2:00 PM','Lunch'],['2:00 PM – 4:00 PM','Career Growth Study'],['4:00 PM – 5:00 PM','Workout'],['5:00 PM – 8:00 PM','Family Time'],['8:00 PM – 9:00 PM','Dinner'],['9:00 PM – 10:00 PM','Planning'],['10:30 PM','Sleep']),'Festival':items(['Flexible Day','Habits'],['Flexible Day','Self Care'],['Flexible Day','Family Time'],['Flexible Day','Roadmap Progress']),'Exam Mode':items(['4:30 AM','Wake Up'],['5:00 AM – 7:30 AM','Revision'],['7:30 AM – 8:30 AM','Breakfast'],['9:00 AM – 4:00 PM','College / Exam'],['4:30 PM – 6:30 PM','Revision'],['6:30 PM – 7:30 PM','Dinner'],['7:30 PM – 9:30 PM','Practice Questions'],['9:30 PM','Sleep Preparation'])});
const initial=():Store=>({version:3,profile:{name:'',monthlyGoal:'',defaultMode:'College Day'},phases:[{id:uid(),name:'Become Comfortable With Coding',areas:['Java','DSA','Git & GitHub','AI Tools'].map(name=>createArea(name))},{id:uid(),name:'Build Consistency',areas:['SQL','Python','Pandas','NumPy','Data Cleaning','APIs','Mini Projects'].map(name=>createArea(name))},{id:uid(),name:'Create & Apply',areas:['Power BI','ETL','AWS','Docker','Portfolio','Resume','LinkedIn'].map(name=>createArea(name))},{id:uid(),name:'Keep Growing',areas:['Apache Spark','Airflow','Cloud Data Engineering','Interview Preparation','System Design','Internship Applications','Placement Preparation'].map(name=>createArea(name))}],habits:{},studyDays:{},todayPlan:blankPlan('College Day'),tomorrowPlan:blankPlan('College Day'),planDate:dateKey(),timetables:defaultTimetables(),workoutDefaults:workoutDefaults(),weeklyWorkouts:weeklyWorkouts(),periodWorkouts:periodWorkouts(),periodMode:{enabled:false,startDate:''},hairWashDays:[1,4],hairOilDays:[0]});
function normalize(raw:any):Store {const base=initial();if(!raw?.phases)return base;const exam=raw.timetables?.['Exam Mode']||raw.timetables?.Exam||base.timetables['Exam Mode'];const fixPlan=(p:any)=>({...blankPlan(p?.mode==='Exam'?'Exam Mode':p?.mode||'College Day'),...p,mode:p?.mode==='Exam'?'Exam Mode':p?.mode||'College Day',learningAreaId:p?.learningAreaId||''});return {version:3,profile:{name:raw.profile?.name||'',monthlyGoal:raw.profile?.monthlyGoal||'',defaultMode:raw.profile?.defaultMode==='Exam'?'Exam Mode':raw.profile?.defaultMode||'College Day'},phases:raw.phases,habits:raw.habits||{},studyDays:raw.studyDays||{},todayPlan:fixPlan(raw.todayPlan),tomorrowPlan:fixPlan(raw.tomorrowPlan),planDate:raw.planDate||dateKey(),timetables:{...base.timetables,...raw.timetables,'Exam Mode':exam},workoutDefaults:{...base.workoutDefaults,...raw.workoutDefaults},weeklyWorkouts:raw.weeklyWorkouts||base.weeklyWorkouts,periodWorkouts:raw.periodWorkouts||base.periodWorkouts,periodMode:raw.periodMode||base.periodMode,hairWashDays:raw.hairWashDays||[1,4],hairOilDays:raw.hairOilDays||[0]}}
function restore():Store {try {const raw=localStorage.getItem(key)||localStorage.getItem(legacyKey);if(!raw)return initial();const saved=normalize(JSON.parse(raw));return saved.planDate===dateKey()?saved:{...saved,todayPlan:saved.tomorrowPlan,planDate:dateKey()}}catch{return initial()}}
const Ctx=createContext<{data:Store;setData:Dispatch<SetStateAction<Store>>}|null>(null);
export function StoreProvider({children}:{children:ReactNode}){const [data,setRaw]=useState<Store>(restore);const roll=(current:Store)=>{const today=dateKey(),started=current.periodMode.startDate?Math.floor((new Date(today).getTime()-new Date(current.periodMode.startDate).getTime())/86400000):0,periodMode=current.periodMode.enabled&&started>=5?{enabled:false,startDate:''}:current.periodMode;return current.planDate===today?{...current,periodMode}:{...current,periodMode,studyDays:{...current.studyDays,[current.planDate]:Boolean(current.todayPlan.learningAreaId)},todayPlan:current.tomorrowPlan,planDate:today}};const hasPlan=(plan:Plan)=>Boolean(plan.focus||plan.priority||plan.study||plan.learningAreaId);const setData:Dispatch<SetStateAction<Store>>=(updater)=>setRaw(current=>{const next=roll(typeof updater==='function'?(updater as (d:Store)=>Store)(current):updater);return !hasPlan(next.todayPlan)&&hasPlan(next.tomorrowPlan)?{...next,todayPlan:next.tomorrowPlan}:next});useEffect(()=>localStorage.setItem(key,JSON.stringify(data)),[data]);useEffect(()=>{const id=window.setInterval(()=>setRaw(roll),60000);return()=>window.clearInterval(id)},[]);return <Ctx.Provider value={{data,setData}}>{children}</Ctx.Provider>}
export function useStore(){const v=useContext(Ctx);if(!v)throw new Error('Store missing');return v}
export const completed=(a:Area)=>a.topics.filter(t=>t.done).length;
export const completion=(a:Area)=>a.planned?Math.min(100,Math.round(completed(a)/a.planned*100)):0;
export const phaseTotals=(areas:Area[])=>({done:areas.reduce((s,a)=>s+completed(a),0),planned:areas.reduce((s,a)=>s+a.planned,0)});
export const resizeArea=(area:Area,requested:number):Area=>({...area,planned:Math.max(completed(area),requested,1)});
export function useProgress(){const {data}=useStore();return useMemo(()=>{const totals=phaseTotals(data.phases.flatMap(p=>p.areas));return {...totals,pct:totals.planned?Math.min(100,Math.round(totals.done/totals.planned*100)):0}},[data])}
